<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[2]=array(0,1,1,'5paw6Ze76LWE6K6v');
$cfg_Cs[3]=array(0,1,1,'5pyN5Yqh6aG555uu');
$cfg_Cs[4]=array(0,1,1,'6Kej5Yaz5pa55qGI');
$cfg_Cs[5]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[6]=array(2,1,1,'M0TmiZPljbDnmb7np5E=');
$cfg_Cs[7]=array(3,1,1,'M0TmiZPljbA=');
$cfg_Cs[8]=array(3,1,1,'5LiJ57u05omr5o+P');
$cfg_Cs[9]=array(3,1,1,'5pWZ6IKy5Z+56K6t');
$cfg_Cs[10]=array(3,1,1,'6K6+5aSH6ZSA5ZSu');
$cfg_Cs[11]=array(4,1,1,'5a6255So55S15Zmo');
$cfg_Cs[12]=array(4,1,1,'5rG96L2m6Zu26YOo5Lu2');
$cfg_Cs[14]=array(0,1,1,'5qGI5L6L5LuL57uN');
?>