<?php
$z[0]=Array("global","",811,838);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",1364,1391);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("channel","\r\n                        <a title=\"[field:typename/]\" class=\"a_link \" href=\"[field:typeurl/]\">[field:typename/]</a><span>|</span>\r\n                        ",1491,1694);
$z[2][4]['row']="5";
$z[2][4]['type']="top";
$z[3]=Array("global","",1898,1925);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("global","",2458,2485);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("channel","\r\n                    <a title=\"[field:typename/]\" class=\"a_link\" href=\"[field:typeurl/]\">[field:typename/]</a>\r\n                    ",2561,2741);
$z[5][4]['row']="5";
$z[5][4]['type']="top";

?>