<?php
$z[0]=Array("field","",73,95);
$z[0][4]['name']="typename";
$z[1]=Array("channel","\r\n                    <li>\r\n                        <a title=\"[field:typename/]\" href=\"[field:typeurl/]\"><i></i><span>[field:typename/]</span></a>\r\n                        <ul class=\"frame_title3\"></ul>\r\n                    </li>\r\n                    ",161,458);
$z[1][4]['row']="";
$z[1][4]['type']="son";

?>